-- create sequence regul.tablename_id_seq;
-- create table regul.tablename
-- (
--     id                           bigint default nextval('regul.tablename_id_seq'::regclass)
--         constraint tablename_pk
--             primary key,
--     col1                     varchar,
--     col2                     varchar,
--     col3                     varchar,
--     tablenameparent_id                    bigint
--         constraint tablenameparent_fk_id
--             references regul.tablenameparent
-- );

